export const LOAD_FEEDS = 'LOAD_FEEDS';
export const LOAD_FEEDS_SUCCESS = 'LOAD_FEEDS_SUCCESS';
export const LOAD_FEEDS_FAILURE = 'LOAD_FEEDS_FAILURE';

export const SELECT_FEED = 'SELECT_FEED';

export const LOAD_FEED = 'LOAD_FEED';
export const LOAD_FEED_START = 'LOAD_FEED_START';
export const LOAD_FEED_SUCCESS = 'LOAD_FEED_SUCCESS';
export const LOAD_FEED_FAILURE = 'LOAD_FEED_FAILURE';
export const LOAD_FEED_END = 'LOAD_FEED_END';

export const UPDATE_FEED = 'UPDATE_FEED';
export const UPDATE_FEED_START = 'UPDATE_START';
export const UPDATE_FEED_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FEED_FAILURE = 'UPDATE_FAILURE';
export const UPDATE_FEED_END = 'UPDATE_END';

export const SELECT_POST = 'SELECT_POST';

export const MARK_READ = 'MARK_READ';
export const MARK_READ_FAILURE = 'MARK_READ_FAILURE';
